BEGIN;
DROP TABLE IF EXISTS image_store CASCADE;

DROP TABLE IF EXISTS cuisines CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS recipes CASCADE;

DROP TABLE IF EXISTS ingredients CASCADE;

DROP TABLE IF EXISTS saved_recipes CASCADE;

DROP TABLE IF EXISTS recipe_ingredients CASCADE;
COMMIT;