BEGIN;
TRUNCATE TABLE saved_recipes CASCADE;
TRUNCATE TABLE ingredients CASCADE;
TRUNCATE TABLE recipe_ingredients CASCADE;
TRUNCATE TABLE recipes CASCADE;
TRUNCATE TABLE image_store CASCADE;
TRUNCATE TABLE cuisines CASCADE;
TRUNCATE TABLE users CASCADE;
COMMIT;