stages:
  - build
  - staging
  - production

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:production" Server/src/.
    - docker push "$CI_REGISTRY_IMAGE:production"
  only:
    - master
    - develop

docker-production:
  # Official docker image.
  image: docker:latest
  stage: production
  services:
    - docker:dind
  environment:
    name: production
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - apk add --update python python-dev py-pip
    - pip install awscli --upgrade
    - docker pull $CI_REGISTRY_IMAGE:production
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - $(aws ecr get-login --no-include-email --region $AWS_REGION)
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $AWS_REGISTRY_IMAGE:production
    - docker push $AWS_REGISTRY_IMAGE:production
    - aws ecs register-task-definition --family boncuisine-production-definition --requires-compatibilities FARGATE --cpu 256 --memory 512 --cli-input-json file://deploy-aws.json --region \$AWS_REGION
    - aws ecs update-service --cluster golang-cluster --service golang-container-prod-service --task-definition boncuisine-production-definition --region \$AWS_REGION
  only:
    - develop