stages:
  - build
  - staging
  - production

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:production" Server/src/.
    - docker push "$CI_REGISTRY_IMAGE:production"
  only:
    - master
    - develop
  when:
    manual

docker-production:
  # Official docker image.
  image: docker:latest
  stage: production
  services:
    - docker:dind
  environment:
    name: staging
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - deploy.sh
  only:
    - develop
  when:
    manual