// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname             string   `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	CreatedOn            string   `protobuf:"bytes,6,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

type SavedRecipe struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecipeId             int64    `protobuf:"varint,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SavedRecipe) Reset()         { *m = SavedRecipe{} }
func (m *SavedRecipe) String() string { return proto.CompactTextString(m) }
func (*SavedRecipe) ProtoMessage()    {}
func (*SavedRecipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *SavedRecipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedRecipe.Unmarshal(m, b)
}
func (m *SavedRecipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedRecipe.Marshal(b, m, deterministic)
}
func (m *SavedRecipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedRecipe.Merge(m, src)
}
func (m *SavedRecipe) XXX_Size() int {
	return xxx_messageInfo_SavedRecipe.Size(m)
}
func (m *SavedRecipe) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedRecipe.DiscardUnknown(m)
}

var xxx_messageInfo_SavedRecipe proto.InternalMessageInfo

func (m *SavedRecipe) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SavedRecipe) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type GetSavedRecipiesRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSavedRecipiesRequest) Reset()         { *m = GetSavedRecipiesRequest{} }
func (m *GetSavedRecipiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetSavedRecipiesRequest) ProtoMessage()    {}
func (*GetSavedRecipiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *GetSavedRecipiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSavedRecipiesRequest.Unmarshal(m, b)
}
func (m *GetSavedRecipiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSavedRecipiesRequest.Marshal(b, m, deterministic)
}
func (m *GetSavedRecipiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSavedRecipiesRequest.Merge(m, src)
}
func (m *GetSavedRecipiesRequest) XXX_Size() int {
	return xxx_messageInfo_GetSavedRecipiesRequest.Size(m)
}
func (m *GetSavedRecipiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSavedRecipiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSavedRecipiesRequest proto.InternalMessageInfo

func (m *GetSavedRecipiesRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetSavedRecipiesResponse struct {
	SavedRecipes         []*SavedRecipe `protobuf:"bytes,1,rep,name=savedRecipes,proto3" json:"savedRecipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetSavedRecipiesResponse) Reset()         { *m = GetSavedRecipiesResponse{} }
func (m *GetSavedRecipiesResponse) String() string { return proto.CompactTextString(m) }
func (*GetSavedRecipiesResponse) ProtoMessage()    {}
func (*GetSavedRecipiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *GetSavedRecipiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSavedRecipiesResponse.Unmarshal(m, b)
}
func (m *GetSavedRecipiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSavedRecipiesResponse.Marshal(b, m, deterministic)
}
func (m *GetSavedRecipiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSavedRecipiesResponse.Merge(m, src)
}
func (m *GetSavedRecipiesResponse) XXX_Size() int {
	return xxx_messageInfo_GetSavedRecipiesResponse.Size(m)
}
func (m *GetSavedRecipiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSavedRecipiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSavedRecipiesResponse proto.InternalMessageInfo

func (m *GetSavedRecipiesResponse) GetSavedRecipes() []*SavedRecipe {
	if m != nil {
		return m.SavedRecipes
	}
	return nil
}

type AddSavedRecipeRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecipeId             int64    `protobuf:"varint,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSavedRecipeRequest) Reset()         { *m = AddSavedRecipeRequest{} }
func (m *AddSavedRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*AddSavedRecipeRequest) ProtoMessage()    {}
func (*AddSavedRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *AddSavedRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSavedRecipeRequest.Unmarshal(m, b)
}
func (m *AddSavedRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSavedRecipeRequest.Marshal(b, m, deterministic)
}
func (m *AddSavedRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSavedRecipeRequest.Merge(m, src)
}
func (m *AddSavedRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_AddSavedRecipeRequest.Size(m)
}
func (m *AddSavedRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSavedRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSavedRecipeRequest proto.InternalMessageInfo

func (m *AddSavedRecipeRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddSavedRecipeRequest) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type AddSavedRecipeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSavedRecipeResponse) Reset()         { *m = AddSavedRecipeResponse{} }
func (m *AddSavedRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*AddSavedRecipeResponse) ProtoMessage()    {}
func (*AddSavedRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *AddSavedRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSavedRecipeResponse.Unmarshal(m, b)
}
func (m *AddSavedRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSavedRecipeResponse.Marshal(b, m, deterministic)
}
func (m *AddSavedRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSavedRecipeResponse.Merge(m, src)
}
func (m *AddSavedRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_AddSavedRecipeResponse.Size(m)
}
func (m *AddSavedRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSavedRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSavedRecipeResponse proto.InternalMessageInfo

func (m *AddSavedRecipeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RemoveSavedRecipeRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecipeId             int64    `protobuf:"varint,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSavedRecipeRequest) Reset()         { *m = RemoveSavedRecipeRequest{} }
func (m *RemoveSavedRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveSavedRecipeRequest) ProtoMessage()    {}
func (*RemoveSavedRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *RemoveSavedRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSavedRecipeRequest.Unmarshal(m, b)
}
func (m *RemoveSavedRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSavedRecipeRequest.Marshal(b, m, deterministic)
}
func (m *RemoveSavedRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSavedRecipeRequest.Merge(m, src)
}
func (m *RemoveSavedRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveSavedRecipeRequest.Size(m)
}
func (m *RemoveSavedRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSavedRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSavedRecipeRequest proto.InternalMessageInfo

func (m *RemoveSavedRecipeRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RemoveSavedRecipeRequest) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type RemoveSavedRecipeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSavedRecipeResponse) Reset()         { *m = RemoveSavedRecipeResponse{} }
func (m *RemoveSavedRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveSavedRecipeResponse) ProtoMessage()    {}
func (*RemoveSavedRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *RemoveSavedRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSavedRecipeResponse.Unmarshal(m, b)
}
func (m *RemoveSavedRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSavedRecipeResponse.Marshal(b, m, deterministic)
}
func (m *RemoveSavedRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSavedRecipeResponse.Merge(m, src)
}
func (m *RemoveSavedRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveSavedRecipeResponse.Size(m)
}
func (m *RemoveSavedRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSavedRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSavedRecipeResponse proto.InternalMessageInfo

func (m *RemoveSavedRecipeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "account.User")
	proto.RegisterType((*SavedRecipe)(nil), "account.SavedRecipe")
	proto.RegisterType((*GetSavedRecipiesRequest)(nil), "account.GetSavedRecipiesRequest")
	proto.RegisterType((*GetSavedRecipiesResponse)(nil), "account.GetSavedRecipiesResponse")
	proto.RegisterType((*AddSavedRecipeRequest)(nil), "account.AddSavedRecipeRequest")
	proto.RegisterType((*AddSavedRecipeResponse)(nil), "account.AddSavedRecipeResponse")
	proto.RegisterType((*RemoveSavedRecipeRequest)(nil), "account.RemoveSavedRecipeRequest")
	proto.RegisterType((*RemoveSavedRecipeResponse)(nil), "account.RemoveSavedRecipeResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x6d, 0xf9, 0xdb, 0x41, 0x31, 0x6e, 0x50, 0xd6, 0x1a, 0xb5, 0xee, 0x89, 0x13, 0x07,
	0x8c, 0x89, 0x57, 0xf4, 0x60, 0x38, 0x18, 0x4d, 0xd1, 0xc4, 0x18, 0x13, 0x52, 0xbb, 0x63, 0xd2,
	0x04, 0xda, 0xda, 0x69, 0xf1, 0xd3, 0x18, 0xbf, 0xaa, 0x69, 0x4b, 0x0b, 0x08, 0x85, 0x8b, 0xc7,
	0xd7, 0x37, 0xf3, 0xfa, 0xdb, 0xb7, 0x59, 0xd8, 0xb3, 0x6c, 0xdb, 0x8b, 0xdc, 0xb0, 0xeb, 0x07,
	0x5e, 0xe8, 0xb1, 0xda, 0x4c, 0x8a, 0x1f, 0x05, 0xca, 0xcf, 0x84, 0x01, 0x6b, 0x82, 0xea, 0x48,
	0xae, 0x18, 0x4a, 0xa7, 0x64, 0xaa, 0x8e, 0x64, 0x3a, 0xd4, 0x3f, 0xa2, 0xf1, 0xd8, 0xb5, 0x26,
	0xc8, 0x55, 0x43, 0xe9, 0x68, 0x66, 0xae, 0x63, 0x2f, 0x22, 0x0c, 0x12, 0xaf, 0x94, 0x7a, 0x99,
	0x66, 0x2d, 0xa8, 0xe0, 0xc4, 0x72, 0xc6, 0xbc, 0x9c, 0x18, 0xa9, 0x88, 0x37, 0x7c, 0x8b, 0xe8,
	0xcb, 0x0b, 0x24, 0xaf, 0xa4, 0x1b, 0x99, 0x66, 0xa7, 0x00, 0x76, 0x80, 0x56, 0x88, 0x72, 0xe4,
	0xb9, 0xbc, 0x9a, 0xb8, 0xda, 0xec, 0xcb, 0x83, 0x2b, 0x6e, 0xa1, 0x31, 0xb4, 0xa6, 0x28, 0x4d,
	0xb4, 0x1d, 0x1f, 0x59, 0x1b, 0x6a, 0xf1, 0xbf, 0x46, 0x39, 0x6c, 0x35, 0x96, 0x03, 0xc9, 0x4e,
	0x40, 0x0b, 0x92, 0x91, 0xd8, 0x52, 0x13, 0xab, 0x9e, 0x7e, 0x18, 0x48, 0xd1, 0x83, 0xf6, 0x1d,
	0x86, 0xf3, 0x1c, 0x07, 0xc9, 0xc4, 0xcf, 0x08, 0x29, 0x2c, 0x0c, 0x14, 0x4f, 0xc0, 0x57, 0x77,
	0xc8, 0xf7, 0x5c, 0x42, 0x76, 0x0d, 0xbb, 0x34, 0x87, 0x22, 0xae, 0x18, 0xa5, 0x4e, 0xa3, 0xd7,
	0xea, 0x66, 0x2d, 0x2f, 0x10, 0x9b, 0x4b, 0x93, 0xe2, 0x1e, 0x0e, 0xfb, 0x52, 0x2e, 0xfa, 0x5b,
	0x38, 0xb6, 0x1d, 0xec, 0xe8, 0x6f, 0xdc, 0x0c, 0x91, 0x43, 0x8d, 0x22, 0xdb, 0x46, 0xa2, 0x24,
	0xaf, 0x6e, 0x66, 0x52, 0x3c, 0x02, 0x37, 0x71, 0xe2, 0x4d, 0xf1, 0xdf, 0x28, 0xae, 0xe0, 0x78,
	0x4d, 0xe2, 0x36, 0x90, 0xde, 0xb7, 0x0a, 0xcd, 0x7e, 0xda, 0xd8, 0x10, 0x83, 0xa9, 0x63, 0x23,
	0x7b, 0x81, 0xfd, 0xa5, 0xd2, 0x91, 0x98, 0x91, 0xb7, 0x5a, 0x70, 0x85, 0xfa, 0xc5, 0x86, 0x89,
	0x14, 0x42, 0xec, 0xb0, 0x21, 0x34, 0x97, 0x9b, 0x62, 0x67, 0xf9, 0xda, 0xda, 0x1b, 0xd1, 0xcf,
	0x0b, 0xfd, 0x3c, 0xf4, 0x0d, 0x0e, 0x56, 0x0e, 0xce, 0xe6, 0x38, 0x45, 0x35, 0xeb, 0x62, 0xd3,
	0x48, 0x96, 0x7e, 0xa3, 0xbd, 0x66, 0xef, 0xf4, 0xbd, 0x9a, 0xbc, 0xdb, 0xcb, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf5, 0x87, 0x9f, 0x22, 0xc8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	GetSavedRecipes(ctx context.Context, in *GetSavedRecipiesRequest, opts ...grpc.CallOption) (*GetSavedRecipiesResponse, error)
	AddSavedRecipe(ctx context.Context, in *AddSavedRecipeRequest, opts ...grpc.CallOption) (*AddSavedRecipeResponse, error)
	RemoveSavedRecipe(ctx context.Context, in *RemoveSavedRecipeRequest, opts ...grpc.CallOption) (*RemoveSavedRecipeResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetSavedRecipes(ctx context.Context, in *GetSavedRecipiesRequest, opts ...grpc.CallOption) (*GetSavedRecipiesResponse, error) {
	out := new(GetSavedRecipiesResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetSavedRecipes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AddSavedRecipe(ctx context.Context, in *AddSavedRecipeRequest, opts ...grpc.CallOption) (*AddSavedRecipeResponse, error) {
	out := new(AddSavedRecipeResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/AddSavedRecipe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) RemoveSavedRecipe(ctx context.Context, in *RemoveSavedRecipeRequest, opts ...grpc.CallOption) (*RemoveSavedRecipeResponse, error) {
	out := new(RemoveSavedRecipeResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/RemoveSavedRecipe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	GetSavedRecipes(context.Context, *GetSavedRecipiesRequest) (*GetSavedRecipiesResponse, error)
	AddSavedRecipe(context.Context, *AddSavedRecipeRequest) (*AddSavedRecipeResponse, error)
	RemoveSavedRecipe(context.Context, *RemoveSavedRecipeRequest) (*RemoveSavedRecipeResponse, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) GetSavedRecipes(ctx context.Context, req *GetSavedRecipiesRequest) (*GetSavedRecipiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSavedRecipes not implemented")
}
func (*UnimplementedAccountServiceServer) AddSavedRecipe(ctx context.Context, req *AddSavedRecipeRequest) (*AddSavedRecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSavedRecipe not implemented")
}
func (*UnimplementedAccountServiceServer) RemoveSavedRecipe(ctx context.Context, req *RemoveSavedRecipeRequest) (*RemoveSavedRecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSavedRecipe not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetSavedRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSavedRecipiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetSavedRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetSavedRecipes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetSavedRecipes(ctx, req.(*GetSavedRecipiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AddSavedRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSavedRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AddSavedRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/AddSavedRecipe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AddSavedRecipe(ctx, req.(*AddSavedRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_RemoveSavedRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSavedRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).RemoveSavedRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/RemoveSavedRecipe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).RemoveSavedRecipe(ctx, req.(*RemoveSavedRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSavedRecipes",
			Handler:    _AccountService_GetSavedRecipes_Handler,
		},
		{
			MethodName: "AddSavedRecipe",
			Handler:    _AccountService_AddSavedRecipe_Handler,
		},
		{
			MethodName: "RemoveSavedRecipe",
			Handler:    _AccountService_RemoveSavedRecipe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
