// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname             string   `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	CreatedOn            string   `protobuf:"bytes,6,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

type SavedRecipe struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecipeId             int64    `protobuf:"varint,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SavedRecipe) Reset()         { *m = SavedRecipe{} }
func (m *SavedRecipe) String() string { return proto.CompactTextString(m) }
func (*SavedRecipe) ProtoMessage()    {}
func (*SavedRecipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SavedRecipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedRecipe.Unmarshal(m, b)
}
func (m *SavedRecipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedRecipe.Marshal(b, m, deterministic)
}
func (m *SavedRecipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedRecipe.Merge(m, src)
}
func (m *SavedRecipe) XXX_Size() int {
	return xxx_messageInfo_SavedRecipe.Size(m)
}
func (m *SavedRecipe) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedRecipe.DiscardUnknown(m)
}

var xxx_messageInfo_SavedRecipe proto.InternalMessageInfo

func (m *SavedRecipe) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SavedRecipe) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type GetSavedRecipiesRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSavedRecipiesRequest) Reset()         { *m = GetSavedRecipiesRequest{} }
func (m *GetSavedRecipiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetSavedRecipiesRequest) ProtoMessage()    {}
func (*GetSavedRecipiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetSavedRecipiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSavedRecipiesRequest.Unmarshal(m, b)
}
func (m *GetSavedRecipiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSavedRecipiesRequest.Marshal(b, m, deterministic)
}
func (m *GetSavedRecipiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSavedRecipiesRequest.Merge(m, src)
}
func (m *GetSavedRecipiesRequest) XXX_Size() int {
	return xxx_messageInfo_GetSavedRecipiesRequest.Size(m)
}
func (m *GetSavedRecipiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSavedRecipiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSavedRecipiesRequest proto.InternalMessageInfo

func (m *GetSavedRecipiesRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetSavedRecipiesResponse struct {
	SavedRecipes         []*SavedRecipe `protobuf:"bytes,1,rep,name=savedRecipes,proto3" json:"savedRecipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetSavedRecipiesResponse) Reset()         { *m = GetSavedRecipiesResponse{} }
func (m *GetSavedRecipiesResponse) String() string { return proto.CompactTextString(m) }
func (*GetSavedRecipiesResponse) ProtoMessage()    {}
func (*GetSavedRecipiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetSavedRecipiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSavedRecipiesResponse.Unmarshal(m, b)
}
func (m *GetSavedRecipiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSavedRecipiesResponse.Marshal(b, m, deterministic)
}
func (m *GetSavedRecipiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSavedRecipiesResponse.Merge(m, src)
}
func (m *GetSavedRecipiesResponse) XXX_Size() int {
	return xxx_messageInfo_GetSavedRecipiesResponse.Size(m)
}
func (m *GetSavedRecipiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSavedRecipiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSavedRecipiesResponse proto.InternalMessageInfo

func (m *GetSavedRecipiesResponse) GetSavedRecipes() []*SavedRecipe {
	if m != nil {
		return m.SavedRecipes
	}
	return nil
}

type AddSavedRecipeRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecipeId             int64    `protobuf:"varint,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSavedRecipeRequest) Reset()         { *m = AddSavedRecipeRequest{} }
func (m *AddSavedRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*AddSavedRecipeRequest) ProtoMessage()    {}
func (*AddSavedRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *AddSavedRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSavedRecipeRequest.Unmarshal(m, b)
}
func (m *AddSavedRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSavedRecipeRequest.Marshal(b, m, deterministic)
}
func (m *AddSavedRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSavedRecipeRequest.Merge(m, src)
}
func (m *AddSavedRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_AddSavedRecipeRequest.Size(m)
}
func (m *AddSavedRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSavedRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSavedRecipeRequest proto.InternalMessageInfo

func (m *AddSavedRecipeRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddSavedRecipeRequest) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type AddSavedRecipeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSavedRecipeResponse) Reset()         { *m = AddSavedRecipeResponse{} }
func (m *AddSavedRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*AddSavedRecipeResponse) ProtoMessage()    {}
func (*AddSavedRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *AddSavedRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSavedRecipeResponse.Unmarshal(m, b)
}
func (m *AddSavedRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSavedRecipeResponse.Marshal(b, m, deterministic)
}
func (m *AddSavedRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSavedRecipeResponse.Merge(m, src)
}
func (m *AddSavedRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_AddSavedRecipeResponse.Size(m)
}
func (m *AddSavedRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSavedRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSavedRecipeResponse proto.InternalMessageInfo

func (m *AddSavedRecipeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RemoveSavedRecipeRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecipeId             int64    `protobuf:"varint,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSavedRecipeRequest) Reset()         { *m = RemoveSavedRecipeRequest{} }
func (m *RemoveSavedRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveSavedRecipeRequest) ProtoMessage()    {}
func (*RemoveSavedRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *RemoveSavedRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSavedRecipeRequest.Unmarshal(m, b)
}
func (m *RemoveSavedRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSavedRecipeRequest.Marshal(b, m, deterministic)
}
func (m *RemoveSavedRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSavedRecipeRequest.Merge(m, src)
}
func (m *RemoveSavedRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveSavedRecipeRequest.Size(m)
}
func (m *RemoveSavedRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSavedRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSavedRecipeRequest proto.InternalMessageInfo

func (m *RemoveSavedRecipeRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RemoveSavedRecipeRequest) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type RemoveSavedRecipeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSavedRecipeResponse) Reset()         { *m = RemoveSavedRecipeResponse{} }
func (m *RemoveSavedRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveSavedRecipeResponse) ProtoMessage()    {}
func (*RemoveSavedRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *RemoveSavedRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSavedRecipeResponse.Unmarshal(m, b)
}
func (m *RemoveSavedRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSavedRecipeResponse.Marshal(b, m, deterministic)
}
func (m *RemoveSavedRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSavedRecipeResponse.Merge(m, src)
}
func (m *RemoveSavedRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveSavedRecipeResponse.Size(m)
}
func (m *RemoveSavedRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSavedRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSavedRecipeResponse proto.InternalMessageInfo

func (m *RemoveSavedRecipeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*SavedRecipe)(nil), "user.SavedRecipe")
	proto.RegisterType((*GetSavedRecipiesRequest)(nil), "user.GetSavedRecipiesRequest")
	proto.RegisterType((*GetSavedRecipiesResponse)(nil), "user.GetSavedRecipiesResponse")
	proto.RegisterType((*AddSavedRecipeRequest)(nil), "user.AddSavedRecipeRequest")
	proto.RegisterType((*AddSavedRecipeResponse)(nil), "user.AddSavedRecipeResponse")
	proto.RegisterType((*RemoveSavedRecipeRequest)(nil), "user.RemoveSavedRecipeRequest")
	proto.RegisterType((*RemoveSavedRecipeResponse)(nil), "user.RemoveSavedRecipeResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0xc6, 0x6f, 0x0b, 0x14, 0x38, 0xdc, 0x70, 0xc3, 0xe4, 0x2a, 0x63, 0x11, 0x25, 0x5d, 0xb1,
	0x62, 0x81, 0xe1, 0x01, 0xd4, 0x85, 0x61, 0x41, 0xd4, 0x21, 0xba, 0x70, 0x43, 0x6a, 0xe7, 0x98,
	0x34, 0x81, 0xb6, 0xf6, 0xb4, 0xf8, 0x0a, 0xbe, 0x85, 0xaf, 0x6a, 0x66, 0x4a, 0xf9, 0x23, 0x34,
	0x6c, 0xdc, 0xf5, 0x9b, 0xdf, 0x9c, 0x6f, 0xbe, 0x39, 0xd3, 0x03, 0x90, 0x12, 0xc6, 0x83, 0x28,
	0x0e, 0x93, 0x90, 0x95, 0xd5, 0xb7, 0xf3, 0x65, 0x40, 0xf9, 0x89, 0x30, 0x66, 0x4d, 0x30, 0x7d,
	0xc9, 0x8d, 0x9e, 0xd1, 0x2f, 0x09, 0xd3, 0x97, 0xcc, 0x86, 0xda, 0x5b, 0x3a, 0x9f, 0x07, 0xee,
	0x02, 0xb9, 0xd9, 0x33, 0xfa, 0x75, 0xb1, 0xd6, 0x8a, 0xa9, 0x62, 0xcd, 0x4a, 0x19, 0xcb, 0x35,
	0xfb, 0x0f, 0x15, 0x5c, 0xb8, 0xfe, 0x9c, 0x97, 0x35, 0xc8, 0x84, 0xaa, 0x88, 0x5c, 0xa2, 0x8f,
	0x30, 0x96, 0xbc, 0x92, 0x55, 0xe4, 0x9a, 0x75, 0x01, 0xbc, 0x18, 0xdd, 0x04, 0xe5, 0x2c, 0x0c,
	0xb8, 0xa5, 0x69, 0x7d, 0xb5, 0x72, 0x1f, 0x38, 0xb7, 0xd0, 0x98, 0xba, 0x4b, 0x94, 0x02, 0x3d,
	0x3f, 0x42, 0xd6, 0x86, 0xaa, 0x3a, 0x6b, 0xb6, 0x0e, 0x6b, 0x29, 0x39, 0x96, 0xac, 0x03, 0xf5,
	0x58, 0x6f, 0x51, 0xc8, 0xd4, 0xa8, 0x96, 0x2d, 0x8c, 0xa5, 0x33, 0x84, 0xf6, 0x1d, 0x26, 0x1b,
	0x1f, 0x1f, 0x49, 0xe0, 0x7b, 0x8a, 0x94, 0x14, 0x1a, 0x3a, 0x8f, 0xc0, 0xf7, 0x6b, 0x28, 0x0a,
	0x03, 0x42, 0x36, 0x82, 0xbf, 0xb4, 0x09, 0x45, 0xdc, 0xe8, 0x95, 0xfa, 0x8d, 0x61, 0x6b, 0xa0,
	0xfb, 0xbb, 0x15, 0x57, 0xec, 0x6c, 0x73, 0x26, 0x70, 0x72, 0x2d, 0xe5, 0x36, 0x3f, 0x12, 0xe2,
	0xd8, 0xad, 0x4e, 0x7f, 0xda, 0xad, 0xf2, 0x71, 0xa8, 0x52, 0xea, 0x79, 0x48, 0xa4, 0xfd, 0x6a,
	0x22, 0x97, 0xce, 0x03, 0x70, 0x81, 0x8b, 0x70, 0x89, 0xbf, 0x96, 0x62, 0x04, 0x67, 0x07, 0x1c,
	0x8f, 0x05, 0x19, 0x7e, 0x9a, 0xd0, 0x50, 0x7f, 0xde, 0x14, 0xe3, 0xa5, 0xef, 0x21, 0x13, 0xf0,
	0x6f, 0xa7, 0xdd, 0x48, 0xac, 0x9b, 0xf5, 0xb3, 0xe0, 0xe5, 0xec, 0x8b, 0x22, 0x9c, 0x9d, 0xed,
	0xfc, 0x61, 0x13, 0x68, 0xee, 0x36, 0x88, 0x75, 0xb2, 0x9a, 0x83, 0xaf, 0x60, 0x9f, 0x1f, 0x86,
	0x6b, 0xbb, 0x67, 0x68, 0xed, 0xdd, 0x94, 0xad, 0x52, 0x14, 0x35, 0xd5, 0xbe, 0x2c, 0xe4, 0xb9,
	0xef, 0x8d, 0xf5, 0xa2, 0x87, 0xf1, 0xd5, 0xd2, 0x93, 0x79, 0xf5, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x72, 0x82, 0xc0, 0xea, 0xa7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetSavedRecipes(ctx context.Context, in *GetSavedRecipiesRequest, opts ...grpc.CallOption) (*GetSavedRecipiesResponse, error)
	AddSavedRecipe(ctx context.Context, in *AddSavedRecipeRequest, opts ...grpc.CallOption) (*AddSavedRecipeResponse, error)
	RemoveSavedRecipe(ctx context.Context, in *RemoveSavedRecipeRequest, opts ...grpc.CallOption) (*RemoveSavedRecipeResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetSavedRecipes(ctx context.Context, in *GetSavedRecipiesRequest, opts ...grpc.CallOption) (*GetSavedRecipiesResponse, error) {
	out := new(GetSavedRecipiesResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetSavedRecipes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddSavedRecipe(ctx context.Context, in *AddSavedRecipeRequest, opts ...grpc.CallOption) (*AddSavedRecipeResponse, error) {
	out := new(AddSavedRecipeResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/AddSavedRecipe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveSavedRecipe(ctx context.Context, in *RemoveSavedRecipeRequest, opts ...grpc.CallOption) (*RemoveSavedRecipeResponse, error) {
	out := new(RemoveSavedRecipeResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/RemoveSavedRecipe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetSavedRecipes(context.Context, *GetSavedRecipiesRequest) (*GetSavedRecipiesResponse, error)
	AddSavedRecipe(context.Context, *AddSavedRecipeRequest) (*AddSavedRecipeResponse, error)
	RemoveSavedRecipe(context.Context, *RemoveSavedRecipeRequest) (*RemoveSavedRecipeResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetSavedRecipes(ctx context.Context, req *GetSavedRecipiesRequest) (*GetSavedRecipiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSavedRecipes not implemented")
}
func (*UnimplementedUserServiceServer) AddSavedRecipe(ctx context.Context, req *AddSavedRecipeRequest) (*AddSavedRecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSavedRecipe not implemented")
}
func (*UnimplementedUserServiceServer) RemoveSavedRecipe(ctx context.Context, req *RemoveSavedRecipeRequest) (*RemoveSavedRecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSavedRecipe not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetSavedRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSavedRecipiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetSavedRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetSavedRecipes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetSavedRecipes(ctx, req.(*GetSavedRecipiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddSavedRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSavedRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddSavedRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/AddSavedRecipe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddSavedRecipe(ctx, req.(*AddSavedRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveSavedRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSavedRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveSavedRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/RemoveSavedRecipe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveSavedRecipe(ctx, req.(*RemoveSavedRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSavedRecipes",
			Handler:    _UserService_GetSavedRecipes_Handler,
		},
		{
			MethodName: "AddSavedRecipe",
			Handler:    _UserService_AddSavedRecipe_Handler,
		},
		{
			MethodName: "RemoveSavedRecipe",
			Handler:    _UserService_RemoveSavedRecipe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
