// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recipe.proto

package recipe

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Recipe struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Servings             string   `protobuf:"bytes,4,opt,name=servings,proto3" json:"servings,omitempty"`
	Difficulty           string   `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Cuisine              string   `protobuf:"bytes,6,opt,name=cuisine,proto3" json:"cuisine,omitempty"`
	Image                []byte   `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
func (*Recipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{0}
}

func (m *Recipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe.Unmarshal(m, b)
}
func (m *Recipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe.Marshal(b, m, deterministic)
}
func (m *Recipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe.Merge(m, src)
}
func (m *Recipe) XXX_Size() int {
	return xxx_messageInfo_Recipe.Size(m)
}
func (m *Recipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe proto.InternalMessageInfo

func (m *Recipe) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Recipe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipe) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Recipe) GetServings() string {
	if m != nil {
		return m.Servings
	}
	return ""
}

func (m *Recipe) GetDifficulty() string {
	if m != nil {
		return m.Difficulty
	}
	return ""
}

func (m *Recipe) GetCuisine() string {
	if m != nil {
		return m.Cuisine
	}
	return ""
}

func (m *Recipe) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type Cuisine struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cuisine) Reset()         { *m = Cuisine{} }
func (m *Cuisine) String() string { return proto.CompactTextString(m) }
func (*Cuisine) ProtoMessage()    {}
func (*Cuisine) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{1}
}

func (m *Cuisine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cuisine.Unmarshal(m, b)
}
func (m *Cuisine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cuisine.Marshal(b, m, deterministic)
}
func (m *Cuisine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cuisine.Merge(m, src)
}
func (m *Cuisine) XXX_Size() int {
	return xxx_messageInfo_Cuisine.Size(m)
}
func (m *Cuisine) XXX_DiscardUnknown() {
	xxx_messageInfo_Cuisine.DiscardUnknown(m)
}

var xxx_messageInfo_Cuisine proto.InternalMessageInfo

func (m *Cuisine) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Cuisine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RecipeIngredient struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Image                []byte   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecipeIngredient) Reset()         { *m = RecipeIngredient{} }
func (m *RecipeIngredient) String() string { return proto.CompactTextString(m) }
func (*RecipeIngredient) ProtoMessage()    {}
func (*RecipeIngredient) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{2}
}

func (m *RecipeIngredient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeIngredient.Unmarshal(m, b)
}
func (m *RecipeIngredient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeIngredient.Marshal(b, m, deterministic)
}
func (m *RecipeIngredient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeIngredient.Merge(m, src)
}
func (m *RecipeIngredient) XXX_Size() int {
	return xxx_messageInfo_RecipeIngredient.Size(m)
}
func (m *RecipeIngredient) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeIngredient.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeIngredient proto.InternalMessageInfo

func (m *RecipeIngredient) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RecipeIngredient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecipeIngredient) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RecipeIngredient) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type GetAllRecipeResponse struct {
	Recipes              []*Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAllRecipeResponse) Reset()         { *m = GetAllRecipeResponse{} }
func (m *GetAllRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllRecipeResponse) ProtoMessage()    {}
func (*GetAllRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{3}
}

func (m *GetAllRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRecipeResponse.Unmarshal(m, b)
}
func (m *GetAllRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRecipeResponse.Marshal(b, m, deterministic)
}
func (m *GetAllRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRecipeResponse.Merge(m, src)
}
func (m *GetAllRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllRecipeResponse.Size(m)
}
func (m *GetAllRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRecipeResponse proto.InternalMessageInfo

func (m *GetAllRecipeResponse) GetRecipes() []*Recipe {
	if m != nil {
		return m.Recipes
	}
	return nil
}

type GetRecipeIngredientsRequest struct {
	RecipeId             int64    `protobuf:"varint,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecipeIngredientsRequest) Reset()         { *m = GetRecipeIngredientsRequest{} }
func (m *GetRecipeIngredientsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecipeIngredientsRequest) ProtoMessage()    {}
func (*GetRecipeIngredientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{4}
}

func (m *GetRecipeIngredientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeIngredientsRequest.Unmarshal(m, b)
}
func (m *GetRecipeIngredientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeIngredientsRequest.Marshal(b, m, deterministic)
}
func (m *GetRecipeIngredientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeIngredientsRequest.Merge(m, src)
}
func (m *GetRecipeIngredientsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecipeIngredientsRequest.Size(m)
}
func (m *GetRecipeIngredientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeIngredientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeIngredientsRequest proto.InternalMessageInfo

func (m *GetRecipeIngredientsRequest) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type GetRecipeIngredientsResponse struct {
	RecipeIngredients    []*RecipeIngredient `protobuf:"bytes,1,rep,name=recipeIngredients,proto3" json:"recipeIngredients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetRecipeIngredientsResponse) Reset()         { *m = GetRecipeIngredientsResponse{} }
func (m *GetRecipeIngredientsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecipeIngredientsResponse) ProtoMessage()    {}
func (*GetRecipeIngredientsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{5}
}

func (m *GetRecipeIngredientsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeIngredientsResponse.Unmarshal(m, b)
}
func (m *GetRecipeIngredientsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeIngredientsResponse.Marshal(b, m, deterministic)
}
func (m *GetRecipeIngredientsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeIngredientsResponse.Merge(m, src)
}
func (m *GetRecipeIngredientsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecipeIngredientsResponse.Size(m)
}
func (m *GetRecipeIngredientsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeIngredientsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeIngredientsResponse proto.InternalMessageInfo

func (m *GetRecipeIngredientsResponse) GetRecipeIngredients() []*RecipeIngredient {
	if m != nil {
		return m.RecipeIngredients
	}
	return nil
}

type GetAllCuisinesResponse struct {
	Cuisines             []*Cuisine `protobuf:"bytes,1,rep,name=cuisines,proto3" json:"cuisines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllCuisinesResponse) Reset()         { *m = GetAllCuisinesResponse{} }
func (m *GetAllCuisinesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllCuisinesResponse) ProtoMessage()    {}
func (*GetAllCuisinesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{6}
}

func (m *GetAllCuisinesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCuisinesResponse.Unmarshal(m, b)
}
func (m *GetAllCuisinesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCuisinesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllCuisinesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCuisinesResponse.Merge(m, src)
}
func (m *GetAllCuisinesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllCuisinesResponse.Size(m)
}
func (m *GetAllCuisinesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCuisinesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCuisinesResponse proto.InternalMessageInfo

func (m *GetAllCuisinesResponse) GetCuisines() []*Cuisine {
	if m != nil {
		return m.Cuisines
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{7}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Recipe)(nil), "recipe.Recipe")
	proto.RegisterType((*Cuisine)(nil), "recipe.Cuisine")
	proto.RegisterType((*RecipeIngredient)(nil), "recipe.RecipeIngredient")
	proto.RegisterType((*GetAllRecipeResponse)(nil), "recipe.GetAllRecipeResponse")
	proto.RegisterType((*GetRecipeIngredientsRequest)(nil), "recipe.GetRecipeIngredientsRequest")
	proto.RegisterType((*GetRecipeIngredientsResponse)(nil), "recipe.GetRecipeIngredientsResponse")
	proto.RegisterType((*GetAllCuisinesResponse)(nil), "recipe.GetAllCuisinesResponse")
	proto.RegisterType((*Empty)(nil), "recipe.Empty")
}

func init() { proto.RegisterFile("recipe.proto", fileDescriptor_952719e3f4c063a9) }

var fileDescriptor_952719e3f4c063a9 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xdd, 0x34, 0x6d, 0x92, 0x1d, 0xb6, 0x05, 0xac, 0xd5, 0xca, 0xea, 0xae, 0xaa, 0xc8, 0x70,
	0x88, 0x84, 0xe8, 0xa1, 0xdc, 0x38, 0x20, 0x0a, 0x2a, 0x55, 0xaf, 0xe6, 0xc6, 0x05, 0x95, 0x64,
	0x5a, 0x59, 0x6a, 0x3e, 0x88, 0x1d, 0xa4, 0xfe, 0x27, 0xfe, 0x1f, 0x57, 0x54, 0xdb, 0x49, 0xd3,
	0xb4, 0xa0, 0xde, 0xfc, 0x66, 0xde, 0xcc, 0xbc, 0x79, 0x93, 0xc0, 0x5d, 0x89, 0xb1, 0x28, 0x70,
	0x5a, 0x94, 0xb9, 0xca, 0x89, 0x67, 0x10, 0xfb, 0xed, 0x80, 0xc7, 0xf5, 0x93, 0x8c, 0xa0, 0x27,
	0x12, 0xea, 0x84, 0x4e, 0xe4, 0xf2, 0x9e, 0x48, 0x08, 0x81, 0x7e, 0xb6, 0x4e, 0x91, 0xf6, 0x42,
	0x27, 0xba, 0xe5, 0xfa, 0x7d, 0x88, 0x29, 0x91, 0x22, 0x75, 0x4d, 0xec, 0xf0, 0x26, 0x63, 0x08,
	0x24, 0x96, 0xbf, 0x44, 0xb6, 0x95, 0xb4, 0xaf, 0xe3, 0x0d, 0x26, 0x13, 0x80, 0x44, 0x6c, 0x36,
	0x22, 0xae, 0x76, 0x6a, 0x4f, 0x07, 0x3a, 0xdb, 0x8a, 0x10, 0x0a, 0x7e, 0x5c, 0x09, 0x29, 0x32,
	0xa4, 0x9e, 0x4e, 0xd6, 0x90, 0xdc, 0xc3, 0x40, 0xa4, 0xeb, 0x2d, 0x52, 0x3f, 0x74, 0xa2, 0x3b,
	0x6e, 0x00, 0x7b, 0x0b, 0xfe, 0x67, 0x4b, 0xb8, 0x42, 0x2e, 0x4b, 0xe0, 0x85, 0x59, 0x6e, 0x95,
	0x6d, 0x4b, 0x4c, 0x04, 0x66, 0xea, 0xaa, 0x35, 0x1f, 0xc0, 0x5b, 0xa7, 0x79, 0x95, 0x29, 0xbd,
	0xa8, 0xcb, 0x2d, 0x3a, 0x8a, 0xea, 0xb7, 0x45, 0x7d, 0x84, 0xfb, 0x25, 0xaa, 0xf9, 0x6e, 0x67,
	0x66, 0x71, 0x94, 0x45, 0x9e, 0x49, 0x24, 0x11, 0xf8, 0xc6, 0x65, 0x49, 0x9d, 0xd0, 0x8d, 0x9e,
	0xcd, 0x46, 0x53, 0x7b, 0x03, 0x4b, 0xac, 0xd3, 0xec, 0x3d, 0x3c, 0x2e, 0x51, 0x75, 0xa5, 0x4a,
	0x8e, 0x3f, 0x2b, 0x94, 0x8a, 0x3c, 0xc2, 0xad, 0x61, 0x7e, 0x6f, 0x94, 0x07, 0x26, 0xb0, 0x4a,
	0xd8, 0x06, 0x9e, 0x2e, 0xd7, 0x5a, 0x15, 0x5f, 0xe0, 0x65, 0xd9, 0x4d, 0x5a, 0x3d, 0xf4, 0x54,
	0xcf, 0x91, 0xc0, 0xcf, 0x4b, 0xd8, 0x02, 0x1e, 0xcc, 0x96, 0xf6, 0x00, 0xc7, 0x09, 0x6f, 0x20,
	0xb0, 0x57, 0xab, 0x1b, 0x3f, 0xaf, 0x1b, 0x5b, 0x2e, 0x6f, 0x08, 0xcc, 0x87, 0xc1, 0x22, 0x2d,
	0xd4, 0x7e, 0xf6, 0xc7, 0x81, 0xa1, 0x99, 0xfb, 0xf5, 0xf0, 0xb5, 0xc4, 0x48, 0x3e, 0xc0, 0xb0,
	0xed, 0xa3, 0x24, 0xc3, 0xba, 0x8d, 0xae, 0x18, 0x3f, 0xd5, 0xf0, 0x92, 0xdb, 0xec, 0x86, 0xc4,
	0xfa, 0x0e, 0x67, 0x4e, 0x90, 0x57, 0xad, 0xba, 0x7f, 0x79, 0x3c, 0x7e, 0xfd, 0x7f, 0x52, 0x33,
	0x64, 0x0e, 0xa3, 0x53, 0x1b, 0xba, 0x2a, 0x27, 0xa7, 0x2a, 0xbb, 0x6e, 0xb1, 0x9b, 0x4f, 0xc1,
	0x37, 0xfb, 0xf7, 0xfd, 0xf0, 0xf4, 0xcf, 0xf8, 0xee, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5,
	0xa2, 0xe8, 0x12, 0x9c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecipeServiceClient is the client API for RecipeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecipeServiceClient interface {
	GetAllRecipes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllRecipeResponse, error)
	GetRecipeIngredients(ctx context.Context, in *GetRecipeIngredientsRequest, opts ...grpc.CallOption) (*GetRecipeIngredientsResponse, error)
	GetAllCuisines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllCuisinesResponse, error)
}

type recipeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecipeServiceClient(cc *grpc.ClientConn) RecipeServiceClient {
	return &recipeServiceClient{cc}
}

func (c *recipeServiceClient) GetAllRecipes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllRecipeResponse, error) {
	out := new(GetAllRecipeResponse)
	err := c.cc.Invoke(ctx, "/recipe.RecipeService/GetAllRecipes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetRecipeIngredients(ctx context.Context, in *GetRecipeIngredientsRequest, opts ...grpc.CallOption) (*GetRecipeIngredientsResponse, error) {
	out := new(GetRecipeIngredientsResponse)
	err := c.cc.Invoke(ctx, "/recipe.RecipeService/GetRecipeIngredients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetAllCuisines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllCuisinesResponse, error) {
	out := new(GetAllCuisinesResponse)
	err := c.cc.Invoke(ctx, "/recipe.RecipeService/GetAllCuisines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecipeServiceServer is the server API for RecipeService service.
type RecipeServiceServer interface {
	GetAllRecipes(context.Context, *Empty) (*GetAllRecipeResponse, error)
	GetRecipeIngredients(context.Context, *GetRecipeIngredientsRequest) (*GetRecipeIngredientsResponse, error)
	GetAllCuisines(context.Context, *Empty) (*GetAllCuisinesResponse, error)
}

// UnimplementedRecipeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRecipeServiceServer struct {
}

func (*UnimplementedRecipeServiceServer) GetAllRecipes(ctx context.Context, req *Empty) (*GetAllRecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRecipes not implemented")
}
func (*UnimplementedRecipeServiceServer) GetRecipeIngredients(ctx context.Context, req *GetRecipeIngredientsRequest) (*GetRecipeIngredientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecipeIngredients not implemented")
}
func (*UnimplementedRecipeServiceServer) GetAllCuisines(ctx context.Context, req *Empty) (*GetAllCuisinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCuisines not implemented")
}

func RegisterRecipeServiceServer(s *grpc.Server, srv RecipeServiceServer) {
	s.RegisterService(&_RecipeService_serviceDesc, srv)
}

func _RecipeService_GetAllRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetAllRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.RecipeService/GetAllRecipes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetAllRecipes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetRecipeIngredients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipeIngredientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipeIngredients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.RecipeService/GetRecipeIngredients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipeIngredients(ctx, req.(*GetRecipeIngredientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetAllCuisines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetAllCuisines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.RecipeService/GetAllCuisines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetAllCuisines(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecipeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recipe.RecipeService",
	HandlerType: (*RecipeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllRecipes",
			Handler:    _RecipeService_GetAllRecipes_Handler,
		},
		{
			MethodName: "GetRecipeIngredients",
			Handler:    _RecipeService_GetRecipeIngredients_Handler,
		},
		{
			MethodName: "GetAllCuisines",
			Handler:    _RecipeService_GetAllCuisines_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recipe.proto",
}
