// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recipe.proto

package recipe

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Recipe struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Servings             string   `protobuf:"bytes,4,opt,name=servings,proto3" json:"servings,omitempty"`
	Difficulty           string   `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Cuisine              string   `protobuf:"bytes,6,opt,name=cuisine,proto3" json:"cuisine,omitempty"`
	Image                []byte   `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
func (*Recipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{0}
}

func (m *Recipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe.Unmarshal(m, b)
}
func (m *Recipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe.Marshal(b, m, deterministic)
}
func (m *Recipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe.Merge(m, src)
}
func (m *Recipe) XXX_Size() int {
	return xxx_messageInfo_Recipe.Size(m)
}
func (m *Recipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe proto.InternalMessageInfo

func (m *Recipe) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Recipe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipe) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Recipe) GetServings() string {
	if m != nil {
		return m.Servings
	}
	return ""
}

func (m *Recipe) GetDifficulty() string {
	if m != nil {
		return m.Difficulty
	}
	return ""
}

func (m *Recipe) GetCuisine() string {
	if m != nil {
		return m.Cuisine
	}
	return ""
}

func (m *Recipe) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type Cuisine struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cuisine) Reset()         { *m = Cuisine{} }
func (m *Cuisine) String() string { return proto.CompactTextString(m) }
func (*Cuisine) ProtoMessage()    {}
func (*Cuisine) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{1}
}

func (m *Cuisine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cuisine.Unmarshal(m, b)
}
func (m *Cuisine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cuisine.Marshal(b, m, deterministic)
}
func (m *Cuisine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cuisine.Merge(m, src)
}
func (m *Cuisine) XXX_Size() int {
	return xxx_messageInfo_Cuisine.Size(m)
}
func (m *Cuisine) XXX_DiscardUnknown() {
	xxx_messageInfo_Cuisine.DiscardUnknown(m)
}

var xxx_messageInfo_Cuisine proto.InternalMessageInfo

func (m *Cuisine) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Cuisine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RecipeIngredient struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Image                []byte   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecipeIngredient) Reset()         { *m = RecipeIngredient{} }
func (m *RecipeIngredient) String() string { return proto.CompactTextString(m) }
func (*RecipeIngredient) ProtoMessage()    {}
func (*RecipeIngredient) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{2}
}

func (m *RecipeIngredient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeIngredient.Unmarshal(m, b)
}
func (m *RecipeIngredient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeIngredient.Marshal(b, m, deterministic)
}
func (m *RecipeIngredient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeIngredient.Merge(m, src)
}
func (m *RecipeIngredient) XXX_Size() int {
	return xxx_messageInfo_RecipeIngredient.Size(m)
}
func (m *RecipeIngredient) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeIngredient.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeIngredient proto.InternalMessageInfo

func (m *RecipeIngredient) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RecipeIngredient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecipeIngredient) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RecipeIngredient) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type GetAllRecipeResponse struct {
	Recipes              []*Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAllRecipeResponse) Reset()         { *m = GetAllRecipeResponse{} }
func (m *GetAllRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllRecipeResponse) ProtoMessage()    {}
func (*GetAllRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{3}
}

func (m *GetAllRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRecipeResponse.Unmarshal(m, b)
}
func (m *GetAllRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRecipeResponse.Marshal(b, m, deterministic)
}
func (m *GetAllRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRecipeResponse.Merge(m, src)
}
func (m *GetAllRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllRecipeResponse.Size(m)
}
func (m *GetAllRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRecipeResponse proto.InternalMessageInfo

func (m *GetAllRecipeResponse) GetRecipes() []*Recipe {
	if m != nil {
		return m.Recipes
	}
	return nil
}

type GetRecipeIngredientsRequest struct {
	RecipeId             int64    `protobuf:"varint,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecipeIngredientsRequest) Reset()         { *m = GetRecipeIngredientsRequest{} }
func (m *GetRecipeIngredientsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecipeIngredientsRequest) ProtoMessage()    {}
func (*GetRecipeIngredientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{4}
}

func (m *GetRecipeIngredientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeIngredientsRequest.Unmarshal(m, b)
}
func (m *GetRecipeIngredientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeIngredientsRequest.Marshal(b, m, deterministic)
}
func (m *GetRecipeIngredientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeIngredientsRequest.Merge(m, src)
}
func (m *GetRecipeIngredientsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecipeIngredientsRequest.Size(m)
}
func (m *GetRecipeIngredientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeIngredientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeIngredientsRequest proto.InternalMessageInfo

func (m *GetRecipeIngredientsRequest) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type GetRecipeIngredientsResponse struct {
	RecipeIngredients    []*RecipeIngredient `protobuf:"bytes,1,rep,name=recipeIngredients,proto3" json:"recipeIngredients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetRecipeIngredientsResponse) Reset()         { *m = GetRecipeIngredientsResponse{} }
func (m *GetRecipeIngredientsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecipeIngredientsResponse) ProtoMessage()    {}
func (*GetRecipeIngredientsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{5}
}

func (m *GetRecipeIngredientsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeIngredientsResponse.Unmarshal(m, b)
}
func (m *GetRecipeIngredientsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeIngredientsResponse.Marshal(b, m, deterministic)
}
func (m *GetRecipeIngredientsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeIngredientsResponse.Merge(m, src)
}
func (m *GetRecipeIngredientsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecipeIngredientsResponse.Size(m)
}
func (m *GetRecipeIngredientsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeIngredientsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeIngredientsResponse proto.InternalMessageInfo

func (m *GetRecipeIngredientsResponse) GetRecipeIngredients() []*RecipeIngredient {
	if m != nil {
		return m.RecipeIngredients
	}
	return nil
}

type GetAllCuisinesResponse struct {
	Cuisines             []*Cuisine `protobuf:"bytes,1,rep,name=cuisines,proto3" json:"cuisines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllCuisinesResponse) Reset()         { *m = GetAllCuisinesResponse{} }
func (m *GetAllCuisinesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllCuisinesResponse) ProtoMessage()    {}
func (*GetAllCuisinesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{6}
}

func (m *GetAllCuisinesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCuisinesResponse.Unmarshal(m, b)
}
func (m *GetAllCuisinesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCuisinesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllCuisinesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCuisinesResponse.Merge(m, src)
}
func (m *GetAllCuisinesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllCuisinesResponse.Size(m)
}
func (m *GetAllCuisinesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCuisinesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCuisinesResponse proto.InternalMessageInfo

func (m *GetAllCuisinesResponse) GetCuisines() []*Cuisine {
	if m != nil {
		return m.Cuisines
	}
	return nil
}

type SavedRecipe struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecipeId             int64    `protobuf:"varint,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SavedRecipe) Reset()         { *m = SavedRecipe{} }
func (m *SavedRecipe) String() string { return proto.CompactTextString(m) }
func (*SavedRecipe) ProtoMessage()    {}
func (*SavedRecipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{7}
}

func (m *SavedRecipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedRecipe.Unmarshal(m, b)
}
func (m *SavedRecipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedRecipe.Marshal(b, m, deterministic)
}
func (m *SavedRecipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedRecipe.Merge(m, src)
}
func (m *SavedRecipe) XXX_Size() int {
	return xxx_messageInfo_SavedRecipe.Size(m)
}
func (m *SavedRecipe) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedRecipe.DiscardUnknown(m)
}

var xxx_messageInfo_SavedRecipe proto.InternalMessageInfo

func (m *SavedRecipe) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SavedRecipe) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type GetSavedRecipiesResponse struct {
	SavedRecipes         []*SavedRecipe `protobuf:"bytes,1,rep,name=savedRecipes,proto3" json:"savedRecipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetSavedRecipiesResponse) Reset()         { *m = GetSavedRecipiesResponse{} }
func (m *GetSavedRecipiesResponse) String() string { return proto.CompactTextString(m) }
func (*GetSavedRecipiesResponse) ProtoMessage()    {}
func (*GetSavedRecipiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{8}
}

func (m *GetSavedRecipiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSavedRecipiesResponse.Unmarshal(m, b)
}
func (m *GetSavedRecipiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSavedRecipiesResponse.Marshal(b, m, deterministic)
}
func (m *GetSavedRecipiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSavedRecipiesResponse.Merge(m, src)
}
func (m *GetSavedRecipiesResponse) XXX_Size() int {
	return xxx_messageInfo_GetSavedRecipiesResponse.Size(m)
}
func (m *GetSavedRecipiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSavedRecipiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSavedRecipiesResponse proto.InternalMessageInfo

func (m *GetSavedRecipiesResponse) GetSavedRecipes() []*SavedRecipe {
	if m != nil {
		return m.SavedRecipes
	}
	return nil
}

type AddSavedRecipeRequest struct {
	RecipeId             int64    `protobuf:"varint,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSavedRecipeRequest) Reset()         { *m = AddSavedRecipeRequest{} }
func (m *AddSavedRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*AddSavedRecipeRequest) ProtoMessage()    {}
func (*AddSavedRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{9}
}

func (m *AddSavedRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSavedRecipeRequest.Unmarshal(m, b)
}
func (m *AddSavedRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSavedRecipeRequest.Marshal(b, m, deterministic)
}
func (m *AddSavedRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSavedRecipeRequest.Merge(m, src)
}
func (m *AddSavedRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_AddSavedRecipeRequest.Size(m)
}
func (m *AddSavedRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSavedRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSavedRecipeRequest proto.InternalMessageInfo

func (m *AddSavedRecipeRequest) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type AddSavedRecipeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSavedRecipeResponse) Reset()         { *m = AddSavedRecipeResponse{} }
func (m *AddSavedRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*AddSavedRecipeResponse) ProtoMessage()    {}
func (*AddSavedRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{10}
}

func (m *AddSavedRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSavedRecipeResponse.Unmarshal(m, b)
}
func (m *AddSavedRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSavedRecipeResponse.Marshal(b, m, deterministic)
}
func (m *AddSavedRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSavedRecipeResponse.Merge(m, src)
}
func (m *AddSavedRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_AddSavedRecipeResponse.Size(m)
}
func (m *AddSavedRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSavedRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSavedRecipeResponse proto.InternalMessageInfo

func (m *AddSavedRecipeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RemoveSavedRecipeRequest struct {
	RecipeId             int64    `protobuf:"varint,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSavedRecipeRequest) Reset()         { *m = RemoveSavedRecipeRequest{} }
func (m *RemoveSavedRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveSavedRecipeRequest) ProtoMessage()    {}
func (*RemoveSavedRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{11}
}

func (m *RemoveSavedRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSavedRecipeRequest.Unmarshal(m, b)
}
func (m *RemoveSavedRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSavedRecipeRequest.Marshal(b, m, deterministic)
}
func (m *RemoveSavedRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSavedRecipeRequest.Merge(m, src)
}
func (m *RemoveSavedRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveSavedRecipeRequest.Size(m)
}
func (m *RemoveSavedRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSavedRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSavedRecipeRequest proto.InternalMessageInfo

func (m *RemoveSavedRecipeRequest) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

type RemoveSavedRecipeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSavedRecipeResponse) Reset()         { *m = RemoveSavedRecipeResponse{} }
func (m *RemoveSavedRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveSavedRecipeResponse) ProtoMessage()    {}
func (*RemoveSavedRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{12}
}

func (m *RemoveSavedRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSavedRecipeResponse.Unmarshal(m, b)
}
func (m *RemoveSavedRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSavedRecipeResponse.Marshal(b, m, deterministic)
}
func (m *RemoveSavedRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSavedRecipeResponse.Merge(m, src)
}
func (m *RemoveSavedRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveSavedRecipeResponse.Size(m)
}
func (m *RemoveSavedRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSavedRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSavedRecipeResponse proto.InternalMessageInfo

func (m *RemoveSavedRecipeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{13}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Recipe)(nil), "recipe.Recipe")
	proto.RegisterType((*Cuisine)(nil), "recipe.Cuisine")
	proto.RegisterType((*RecipeIngredient)(nil), "recipe.RecipeIngredient")
	proto.RegisterType((*GetAllRecipeResponse)(nil), "recipe.GetAllRecipeResponse")
	proto.RegisterType((*GetRecipeIngredientsRequest)(nil), "recipe.GetRecipeIngredientsRequest")
	proto.RegisterType((*GetRecipeIngredientsResponse)(nil), "recipe.GetRecipeIngredientsResponse")
	proto.RegisterType((*GetAllCuisinesResponse)(nil), "recipe.GetAllCuisinesResponse")
	proto.RegisterType((*SavedRecipe)(nil), "recipe.SavedRecipe")
	proto.RegisterType((*GetSavedRecipiesResponse)(nil), "recipe.GetSavedRecipiesResponse")
	proto.RegisterType((*AddSavedRecipeRequest)(nil), "recipe.AddSavedRecipeRequest")
	proto.RegisterType((*AddSavedRecipeResponse)(nil), "recipe.AddSavedRecipeResponse")
	proto.RegisterType((*RemoveSavedRecipeRequest)(nil), "recipe.RemoveSavedRecipeRequest")
	proto.RegisterType((*RemoveSavedRecipeResponse)(nil), "recipe.RemoveSavedRecipeResponse")
	proto.RegisterType((*Empty)(nil), "recipe.Empty")
}

func init() { proto.RegisterFile("recipe.proto", fileDescriptor_952719e3f4c063a9) }

var fileDescriptor_952719e3f4c063a9 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0xf3, 0x63, 0x27, 0xd3, 0x24, 0xa5, 0x4b, 0x09, 0x4b, 0x5a, 0x2a, 0xb3, 0x70, 0x88,
	0x84, 0xe8, 0x21, 0x80, 0x2a, 0x71, 0x40, 0x84, 0x52, 0xa2, 0x1c, 0xd9, 0xdc, 0x7a, 0x41, 0xc1,
	0x9e, 0x44, 0x2b, 0xc5, 0x76, 0xf0, 0xda, 0x91, 0xfa, 0x4e, 0x3c, 0x1a, 0x0f, 0x81, 0x62, 0xef,
	0xc6, 0x3f, 0x31, 0xa5, 0xdc, 0x76, 0x66, 0xbe, 0x99, 0xf9, 0x66, 0xe7, 0xdb, 0x85, 0x6e, 0x88,
	0x8e, 0xd8, 0xe0, 0xe5, 0x26, 0x0c, 0xa2, 0x80, 0x98, 0xa9, 0xc5, 0x7e, 0x19, 0x60, 0xf2, 0xe4,
	0x48, 0xfa, 0x50, 0x17, 0x2e, 0x35, 0x6c, 0x63, 0xd4, 0xe0, 0x75, 0xe1, 0x12, 0x02, 0x4d, 0x7f,
	0xe1, 0x21, 0xad, 0xdb, 0xc6, 0xa8, 0xc3, 0x93, 0xf3, 0xce, 0x17, 0x09, 0x0f, 0x69, 0x23, 0xf5,
	0xed, 0xce, 0x64, 0x08, 0x6d, 0x89, 0xe1, 0x56, 0xf8, 0x2b, 0x49, 0x9b, 0x89, 0x7f, 0x6f, 0x93,
	0x0b, 0x00, 0x57, 0x2c, 0x97, 0xc2, 0x89, 0xd7, 0xd1, 0x1d, 0x6d, 0x25, 0xd1, 0x9c, 0x87, 0x50,
	0xb0, 0x9c, 0x58, 0x48, 0xe1, 0x23, 0x35, 0x93, 0xa0, 0x36, 0xc9, 0x29, 0xb4, 0x84, 0xb7, 0x58,
	0x21, 0xb5, 0x6c, 0x63, 0xd4, 0xe5, 0xa9, 0xc1, 0xde, 0x80, 0x75, 0xad, 0x00, 0x0f, 0xa0, 0xcb,
	0x5c, 0x78, 0x94, 0x0e, 0x37, 0xf3, 0x57, 0x21, 0xba, 0x02, 0xfd, 0xe8, 0x41, 0x63, 0x0e, 0xc0,
	0x5c, 0x78, 0x41, 0xec, 0x47, 0xc9, 0xa0, 0x0d, 0xae, 0xac, 0x8c, 0x54, 0x33, 0x4f, 0xea, 0x13,
	0x9c, 0x4e, 0x31, 0x9a, 0xac, 0xd7, 0x69, 0x2f, 0x8e, 0x72, 0x13, 0xf8, 0x12, 0xc9, 0x08, 0xac,
	0xf4, 0x96, 0x25, 0x35, 0xec, 0xc6, 0xe8, 0x68, 0xdc, 0xbf, 0x54, 0x3b, 0x50, 0x40, 0x1d, 0x66,
	0x1f, 0xe0, 0x6c, 0x8a, 0x51, 0x99, 0xaa, 0xe4, 0xf8, 0x33, 0x46, 0x19, 0x91, 0x33, 0xe8, 0xa4,
	0xc8, 0xef, 0x7b, 0xe6, 0xed, 0xd4, 0x31, 0x73, 0xd9, 0x12, 0xce, 0xab, 0x73, 0x15, 0x8b, 0xaf,
	0x70, 0x12, 0x96, 0x83, 0x8a, 0x0f, 0x2d, 0xf2, 0xc9, 0x00, 0xfc, 0x30, 0x85, 0xdd, 0xc0, 0x20,
	0x9d, 0x52, 0x2d, 0x20, 0xeb, 0xf0, 0x1a, 0xda, 0x6a, 0x6b, 0xba, 0xf0, 0xb1, 0x2e, 0xac, 0xb0,
	0x7c, 0x0f, 0x60, 0xd7, 0x70, 0x34, 0x5f, 0x6c, 0xd1, 0x55, 0xa2, 0x7b, 0x0a, 0x56, 0x2c, 0x31,
	0xd4, 0x83, 0x75, 0xb8, 0xb9, 0x33, 0x67, 0x6e, 0x71, 0xe6, 0x7a, 0x69, 0xe6, 0x39, 0xd0, 0x29,
	0x46, 0x59, 0x1d, 0x91, 0x63, 0x73, 0x05, 0x5d, 0x99, 0x35, 0xd0, 0x8c, 0x1e, 0x6b, 0x46, 0xb9,
	0xe6, 0xbc, 0x00, 0x64, 0xef, 0xe0, 0xc9, 0xc4, 0x75, 0xf3, 0xf1, 0xaa, 0xeb, 0x2f, 0x53, 0x19,
	0xc3, 0xa0, 0x9c, 0xa5, 0x88, 0x50, 0xb0, 0x64, 0xec, 0x38, 0x28, 0x65, 0x32, 0x5a, 0x9b, 0x6b,
	0x93, 0x5d, 0x01, 0xe5, 0xe8, 0x05, 0x5b, 0xfc, 0xdf, 0x66, 0xef, 0xe1, 0x59, 0x45, 0xe2, 0x3f,
	0xfb, 0x59, 0xd0, 0xba, 0xf1, 0x36, 0xd1, 0xdd, 0xf8, 0x77, 0x03, 0x7a, 0x69, 0xd6, 0x7c, 0xf7,
	0x42, 0x1d, 0x24, 0x1f, 0xa1, 0x97, 0xd7, 0xae, 0x24, 0x3d, 0x7d, 0x51, 0x49, 0xc6, 0xf0, 0x5c,
	0x9b, 0x55, 0x0a, 0x67, 0x35, 0xe2, 0x24, 0xda, 0x3f, 0x50, 0x1f, 0x79, 0x99, 0xcb, 0xfb, 0x9b,
	0xae, 0x87, 0xaf, 0xee, 0x07, 0xed, 0x9b, 0x4c, 0xa0, 0x5f, 0x94, 0x5e, 0x99, 0xe5, 0x45, 0x91,
	0x65, 0x59, 0xa1, 0xac, 0x46, 0xbe, 0xc0, 0x71, 0x41, 0x31, 0x87, 0x35, 0xec, 0x5c, 0x8d, 0x4a,
	0x65, 0xb1, 0x1a, 0xf9, 0x06, 0xfd, 0xe2, 0xb2, 0xc9, 0x73, 0x9d, 0x55, 0x29, 0x9d, 0x8c, 0x58,
	0xb5, 0x46, 0x58, 0x8d, 0xdc, 0xc2, 0xc9, 0xc1, 0x4a, 0x89, 0x9d, 0x3d, 0xcc, 0x6a, 0x99, 0x0c,
	0x5f, 0xdc, 0x83, 0xd0, 0xb5, 0x3f, 0xb7, 0x6f, 0xd5, 0x37, 0xff, 0xc3, 0x4c, 0x7e, 0xfd, 0xb7,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x47, 0x7b, 0xac, 0xbe, 0x05, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecipeServiceClient is the client API for RecipeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecipeServiceClient interface {
	GetAllRecipes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllRecipeResponse, error)
	GetRecipeIngredients(ctx context.Context, in *GetRecipeIngredientsRequest, opts ...grpc.CallOption) (*GetRecipeIngredientsResponse, error)
	GetAllCuisines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllCuisinesResponse, error)
	GetSavedRecipes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSavedRecipiesResponse, error)
	AddSavedRecipe(ctx context.Context, in *AddSavedRecipeRequest, opts ...grpc.CallOption) (*AddSavedRecipeResponse, error)
	RemoveSavedRecipe(ctx context.Context, in *RemoveSavedRecipeRequest, opts ...grpc.CallOption) (*RemoveSavedRecipeResponse, error)
}

type recipeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecipeServiceClient(cc *grpc.ClientConn) RecipeServiceClient {
	return &recipeServiceClient{cc}
}

func (c *recipeServiceClient) GetAllRecipes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllRecipeResponse, error) {
	out := new(GetAllRecipeResponse)
	err := c.cc.Invoke(ctx, "/recipe.RecipeService/GetAllRecipes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetRecipeIngredients(ctx context.Context, in *GetRecipeIngredientsRequest, opts ...grpc.CallOption) (*GetRecipeIngredientsResponse, error) {
	out := new(GetRecipeIngredientsResponse)
	err := c.cc.Invoke(ctx, "/recipe.RecipeService/GetRecipeIngredients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetAllCuisines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllCuisinesResponse, error) {
	out := new(GetAllCuisinesResponse)
	err := c.cc.Invoke(ctx, "/recipe.RecipeService/GetAllCuisines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) GetSavedRecipes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSavedRecipiesResponse, error) {
	out := new(GetSavedRecipiesResponse)
	err := c.cc.Invoke(ctx, "/recipe.RecipeService/GetSavedRecipes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) AddSavedRecipe(ctx context.Context, in *AddSavedRecipeRequest, opts ...grpc.CallOption) (*AddSavedRecipeResponse, error) {
	out := new(AddSavedRecipeResponse)
	err := c.cc.Invoke(ctx, "/recipe.RecipeService/AddSavedRecipe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) RemoveSavedRecipe(ctx context.Context, in *RemoveSavedRecipeRequest, opts ...grpc.CallOption) (*RemoveSavedRecipeResponse, error) {
	out := new(RemoveSavedRecipeResponse)
	err := c.cc.Invoke(ctx, "/recipe.RecipeService/RemoveSavedRecipe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecipeServiceServer is the server API for RecipeService service.
type RecipeServiceServer interface {
	GetAllRecipes(context.Context, *Empty) (*GetAllRecipeResponse, error)
	GetRecipeIngredients(context.Context, *GetRecipeIngredientsRequest) (*GetRecipeIngredientsResponse, error)
	GetAllCuisines(context.Context, *Empty) (*GetAllCuisinesResponse, error)
	GetSavedRecipes(context.Context, *Empty) (*GetSavedRecipiesResponse, error)
	AddSavedRecipe(context.Context, *AddSavedRecipeRequest) (*AddSavedRecipeResponse, error)
	RemoveSavedRecipe(context.Context, *RemoveSavedRecipeRequest) (*RemoveSavedRecipeResponse, error)
}

// UnimplementedRecipeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRecipeServiceServer struct {
}

func (*UnimplementedRecipeServiceServer) GetAllRecipes(ctx context.Context, req *Empty) (*GetAllRecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRecipes not implemented")
}
func (*UnimplementedRecipeServiceServer) GetRecipeIngredients(ctx context.Context, req *GetRecipeIngredientsRequest) (*GetRecipeIngredientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecipeIngredients not implemented")
}
func (*UnimplementedRecipeServiceServer) GetAllCuisines(ctx context.Context, req *Empty) (*GetAllCuisinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCuisines not implemented")
}
func (*UnimplementedRecipeServiceServer) GetSavedRecipes(ctx context.Context, req *Empty) (*GetSavedRecipiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSavedRecipes not implemented")
}
func (*UnimplementedRecipeServiceServer) AddSavedRecipe(ctx context.Context, req *AddSavedRecipeRequest) (*AddSavedRecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSavedRecipe not implemented")
}
func (*UnimplementedRecipeServiceServer) RemoveSavedRecipe(ctx context.Context, req *RemoveSavedRecipeRequest) (*RemoveSavedRecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSavedRecipe not implemented")
}

func RegisterRecipeServiceServer(s *grpc.Server, srv RecipeServiceServer) {
	s.RegisterService(&_RecipeService_serviceDesc, srv)
}

func _RecipeService_GetAllRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetAllRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.RecipeService/GetAllRecipes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetAllRecipes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetRecipeIngredients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipeIngredientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipeIngredients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.RecipeService/GetRecipeIngredients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipeIngredients(ctx, req.(*GetRecipeIngredientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetAllCuisines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetAllCuisines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.RecipeService/GetAllCuisines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetAllCuisines(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_GetSavedRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetSavedRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.RecipeService/GetSavedRecipes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetSavedRecipes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_AddSavedRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSavedRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).AddSavedRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.RecipeService/AddSavedRecipe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).AddSavedRecipe(ctx, req.(*AddSavedRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_RemoveSavedRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSavedRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).RemoveSavedRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recipe.RecipeService/RemoveSavedRecipe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).RemoveSavedRecipe(ctx, req.(*RemoveSavedRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecipeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recipe.RecipeService",
	HandlerType: (*RecipeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllRecipes",
			Handler:    _RecipeService_GetAllRecipes_Handler,
		},
		{
			MethodName: "GetRecipeIngredients",
			Handler:    _RecipeService_GetRecipeIngredients_Handler,
		},
		{
			MethodName: "GetAllCuisines",
			Handler:    _RecipeService_GetAllCuisines_Handler,
		},
		{
			MethodName: "GetSavedRecipes",
			Handler:    _RecipeService_GetSavedRecipes_Handler,
		},
		{
			MethodName: "AddSavedRecipe",
			Handler:    _RecipeService_AddSavedRecipe_Handler,
		},
		{
			MethodName: "RemoveSavedRecipe",
			Handler:    _RecipeService_RemoveSavedRecipe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recipe.proto",
}
